List<String> searchterms = [
    "all",
    "Coffee",
    "Non Coffee",
    "Cake",
    "Pastry",
    "Pasta",

    "turkish coffee",
    "Mocha",
    "Irish coffee",
    "Latte",
    "Cold Brew",
    "Affogato",
    "Americano",
    "espresso",
    "Macchiato",
    "Cappuccino",
    "Iced coffee",
    "flat white",
    "Nitro coffee",

    "Matcha latte",
    "Iced tea",
    "Lemonade",
    "Hot chocolate",
    "Chai latte",
    "Fruit smoothie",

    "Blueberry",
    "Strawberry",
    "oreo",
    "red velvet",
    "opera",
    "white forest",
    "cherry",
    "black forest",
    "vanilla",
    "chocolate",
    "hazelnut",

    "french pistachio",
    "tender cocnut",
    "choco",

    "salad",
    "sandwich",
    "juice",
    "soup",
    "cup cake",

    "steamed milk",
    "milk",
    "hot",
    "cold",
    "ice-cream",
    "simple",
    "classic",
    "iced",
    "strong",
    "matcha",
    "tea",
    "lemon",
    "cane sugar",
    "black tea",
    "spices",
    "fruits",
    "honey",
    "cocoa",

    "cookies",
    "cheese",
    "Almond",
    "coffee butter cream",
    "white choco",
    "cream",
    "light",
    "fluffy",
    "seasonal",
    "vegetables",
    "fresh",
    "bread",
    "warm",
    "mini cakes",
  ];

  List<String> suggestions = [
    "Coffee",
    "Non Coffee",
    "Cake",
    "Pastry",
    "turkish coffee",
    "Mocha",
    "Irish coffee",
    "Latte",
    "Cold Brew",
    "Affogato",
    "Americano",
    "espresso",
    "Macchiato",
    "Cappuccino",
    "Iced coffee",
    "flat white",
    "Nitro coffee",
    "Matcha latte",
    "Iced tea",
    "Lemonade",
    "Hot chocolate",
    "Chai latte",
    "Fruit smoothie",

    "Blueberry",
    "Strawberry",
    "oreo",
    "red velvet",
    "opera",
    "white forest",
    "cherry",
    "black forest",
    "vanilla",
    "chocolate",
    "hazelnut",

    "french pistachio",
    "tender cocnut",
    "choco",

    "salad",
    "sandwich",
    "juice",
    "soup",
    "cup cake",
  ];