// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRWbLtWuEhfzz6Qkkcb71ImWpnmFh2AdU',
    appId: '1:163638797257:web:3d13e20fc83622010a7e18',
    messagingSenderId: '163638797257',
    projectId: 'solcafe-e700b',
    authDomain: 'solcafe-e700b.firebaseapp.com',
    storageBucket: 'solcafe-e700b.firebasestorage.app',
    measurementId: 'G-M8JBP1RKLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9pYOR2tyZAdZMxbsC8Taq7hmU_Auht4',
    appId: '1:163638797257:android:5daa258d026aa0380a7e18',
    messagingSenderId: '163638797257',
    projectId: 'solcafe-e700b',
    storageBucket: 'solcafe-e700b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgHMugv20SHcQvQA8gbL41z61S25REbys',
    appId: '1:163638797257:ios:4b7cade9df53160e0a7e18',
    messagingSenderId: '163638797257',
    projectId: 'solcafe-e700b',
    storageBucket: 'solcafe-e700b.firebasestorage.app',
    iosBundleId: 'com.example.solcafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgHMugv20SHcQvQA8gbL41z61S25REbys',
    appId: '1:163638797257:ios:4b7cade9df53160e0a7e18',
    messagingSenderId: '163638797257',
    projectId: 'solcafe-e700b',
    storageBucket: 'solcafe-e700b.firebasestorage.app',
    iosBundleId: 'com.example.solcafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRWbLtWuEhfzz6Qkkcb71ImWpnmFh2AdU',
    appId: '1:163638797257:web:03c9bb172d19dd4d0a7e18',
    messagingSenderId: '163638797257',
    projectId: 'solcafe-e700b',
    authDomain: 'solcafe-e700b.firebaseapp.com',
    storageBucket: 'solcafe-e700b.firebasestorage.app',
    measurementId: 'G-HM6V5QJ8JH',
  );
}
